"""Initial

Revision ID: 5566e5969f09
Revises: 
Create Date: 2024-08-31 00:04:03.236319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5566e5969f09'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('controllers',
    sa.Column('mqtt_user', sa.String(), nullable=False),
    sa.Column('mqtt_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('mqtt_user')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_controllers',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('controller_user', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['controller_user'], ['controllers.mqtt_user'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'controller_user')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_controllers')
    op.drop_table('users')
    op.drop_table('controllers')
    # ### end Alembic commands ###
